version: '3.4'

services:
  scheduler:
    image: scheduler
    build:
      context: frontend/node_modules/scheduler
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
